# BAA10Y analysis-agent integration tests

In [ ]:
from __future__ import annotations
import warnings
warnings.filterwarnings('ignore')

import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd
from IPython.display import Markdown, display


def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "aieng-forecasting").is_dir() and (candidate / "implementations").is_dir():
            return candidate
    raise RuntimeError(
        "Repository root not found. Run this notebook from inside the "
        "agentic-forecasting repository."
    )


REPO_ROOT = find_repo_root(Path.cwd().resolve())
IMPLEMENTATIONS_ROOT = REPO_ROOT / "implementations"

if str(IMPLEMENTATIONS_ROOT) not in sys.path:
    sys.path.insert(0, str(IMPLEMENTATIONS_ROOT))

AS_OF = "2026-07-30"
HORIZONS = (1, 5, 21)
PRIMARY_HORIZON = 21
PRIMARY_QUESTION = (
    "Using information available as of July 30, 2026, analyze whether "
    "recent credit-market drivers support BAA10Y widening or tightening "
    "over the next 21 business days."
)

# Opt in only after the no-model tests pass.
RUN_AGENT_TESTS = True

print("Repository root:", REPO_ROOT)
print("As-of date:", AS_OF)
print("Horizons:", HORIZONS)

Repository root: /home/coder/agentic-forecasting
As-of date: 2026-07-30
Horizons: (1, 5, 21)

In [3]:
from aieng.forecasting.evaluation.task import ForecastingTask
from aieng.forecasting.methods.agentic import build_adk_agent
from aieng.forecasting.methods.agentic.adk_runner import (
    AdkTextRunner,
    AdkTextRunnerConfig,
)
from BAA10Y_forecasting.analyst_agent import agent as agent_module
from BAA10Y_forecasting.analyst_agent.agent import (
    BAA10Y_ANALYST_COVARIATE_SERIES_IDS,
    build_baa10y_multitask_news_config,
    load_baa10y_analysis_payload,
)
from BAA10Y_forecasting.data import (
    baa10y_change_series_id,
    build_baa10y_multivariate_service,
)
from BAA10Y_forecasting.tasks import (
    BAA10YMultitaskPromptBuilder,
    TASK_SPECS,
)


def tool_name(tool: Any) -> str:
    name = getattr(tool, "name", None)
    if name:
        return str(name)
    func = getattr(tool, "func", None)
    if func is not None:
        return str(getattr(func, "__name__", type(tool).__name__))
    return str(getattr(tool, "__name__", type(tool).__name__))



print("Loaded agent module:", agent_module.__file__)
print("Loader function:", load_baa10y_analysis_payload.__name__)

Loaded agent module: /home/coder/agentic-forecasting/implementations/BAA10Y_forecasting/analyst_agent/agent.py
Loader function: load_baa10y_analysis_payload

## Test 1 — configuration and final ADK tool registration

This is the fastest diagnostic for the earlier error: `Tool ... not found. Available tools: search_web`. Both assertions must pass before running any model call.

In [3]:
config = build_baa10y_multitask_news_config()
configured_tool_names = [tool_name(tool) for tool in config.function_tools]

adk_agent = build_adk_agent(config)
final_tool_names = [tool_name(tool) for tool in adk_agent.tools]

registration_table = pd.DataFrame(
    [
        {
            "layer": "AgentConfig.function_tools",
            "tools": configured_tool_names,
        },
        {
            "layer": "Built ADK agent.tools",
            "tools": final_tool_names,
        },
    ]
)
display(registration_table)

assert "load_baa10y_analysis_payload" in configured_tool_names, (
    "Loader is missing from AgentConfig.function_tools. Update "
    "build_baa10y_multitask_news_config() in analyst_agent/agent.py."
)
assert "load_baa10y_analysis_payload" in final_tool_names, (
    "Loader did not reach the final ADK agent. Confirm the active agent.py "
    "path above and fully restart ADK Web."
)
assert "search_web" in final_tool_names

print("PASS: search_web and load_baa10y_analysis_payload are registered.")

                        layer                                       tools
0  AgentConfig.function_tools              [load_baa10y_analysis_payload]
1       Built ADK agent.tools  [search_web, load_baa10y_analysis_payload]

PASS: search_web and load_baa10y_analysis_payload are registered.

In [ ]:
for horizon in (1, 5, 21):
    payload = load_baa10y_analysis_payload(
        question=(
            f"Analyze the BAA10Y spread change over the next "
            f"{horizon} business day(s)."
        ),
        as_of=AS_OF,
        horizon_business_days=horizon,
    )

    print(
        {
            "requested_horizon": horizon,
            "task": payload["task"],
        }
    )

## Test 2 — verify parity with `tasks.py`

The interactive loader should reuse `BAA10YMultitaskPromptBuilder`. This test independently builds the same `ForecastContext` and compares the core payload fields.

In [4]:
cutoff = pd.Timestamp(AS_OF).normalize()
service_end = str((cutoff + pd.Timedelta(days=1)).date())
target_series_id = baa10y_change_series_id(PRIMARY_HORIZON)

service = build_baa10y_multivariate_service(
    windows=(PRIMARY_HORIZON,),
    covariate_series_ids=BAA10Y_ANALYST_COVARIATE_SERIES_IDS,
    strict_covariates=False,
    refresh=False,
    end=service_end,
)
context = service.context(cutoff.to_pydatetime())
task = ForecastingTask(
    task_id=f"baa10y_interactive_{PRIMARY_HORIZON}b",
    target_series_id=target_series_id,
    horizons=[PRIMARY_HORIZON],
    frequency="B",
    description=PRIMARY_QUESTION,
)
builder_payload = json.loads(
    BAA10YMultitaskPromptBuilder(task_spec=PRIMARY_QUESTION)(
        task=task,
        context=context,
    )
)
loader_payload = load_baa10y_analysis_payload(
    question=PRIMARY_QUESTION,
    as_of=AS_OF,
    horizon_business_days=PRIMARY_HORIZON,
)

if loader_payload.get("status") != "ok":
    raise RuntimeError(
        "Parity-test loader call failed: "
        + loader_payload.get(
            "message",
            str(loader_payload),
        )
    )
fields_to_compare = [
    "task",
    "task_spec",
    "as_of",
    "origin_target_change_bps",
    "target_history_csv",
    "covariate_history",
]
comparison_rows = []
for field in fields_to_compare:
    matches = loader_payload[field] == builder_payload[field]
    comparison_rows.append({"field": field, "matches": matches})
    assert matches, f"Loader and tasks.py builder differ for {field!r}"

display(pd.DataFrame(comparison_rows))
print("PASS: interactive and predictor payload construction are aligned.")

                      field  matches
0                      task     True
1                 task_spec     True
2                     as_of     True
3  origin_target_change_bps     True
4        target_history_csv     True
5         covariate_history     True

PASS: interactive and predictor payload construction are aligned.

## Test 3 — task-style prompt suite

These prompts exercise statistical analysis, driver interpretation defined in the SKILL.md

In [5]:
SKILL_TEST_CASES = [
    # ============================================================
    # statistical-analysis: three supported diagnostic patterns
    # ============================================================
    {
        "case": "statistical_volatility_regime",
        "skill": "statistical-analysis",
        "type": "volatility_regime",
        "prompt": (
            "Using information available as of July 30, 2026, "
            "classify the volatility regime of the 21-business-day "
            "BAA10Y change series as low, normal, elevated, or extreme. "
            "Report the current 30-observation volatility, median "
            "historical rolling volatility, and volatility ratio."
        ),
    },
    {
        "case": "statistical_anomaly_detection",
        "skill": "statistical-analysis",
        "type": "anomaly_detection",
        "prompt": (
            "Using information available as of July 30, 2026, "
            "determine whether the latest 21-business-day BAA10Y "
            "spread-change observation is anomalous. Report the latest "
            "value, rolling standard deviation, z-score, and whether "
            "the absolute z-score exceeds 2.5."
        ),
    },
    {
        "case": "statistical_window_selection",
        "skill": "statistical-analysis",
        "type": "analysis_window",
        "prompt": (
            "Using information available as of July 30, 2026, "
            "determine whether the statistical analysis should use "
            "15, 30, or 45 recent observations. First calculate the "
            "volatility regime and latest-observation z-score, then "
            "report the selected window, recent median, recent "
            "standard deviation, and selection reason."
        ),
    },
    # ============================================================
    # credit-driver-analysis: three supported analysis patterns
    # ============================================================
    {
        "case": "driver_movement_summary",
        "skill": "credit-driver-analysis",
        "type": "driver_movements",
        "prompt": (
            "Using information available as of July 30, 2026, first "
            "use statistical analysis to select the appropriate "
            "15-, 30-, or 45-observation window. Then summarize the "
            "recent movements of all available BAA10Y credit and "
            "market drivers. Report each driver's treatment, latest "
            "value, net movement, movement z-score, and whether it "
            "is scorable or context only."
        ),
    },
    {
        "case": "driver_evidence_translation",
        "skill": "credit-driver-analysis",
        "type": "widening_tightening_evidence",
        "prompt": (
            "Using information available as of July 30, 2026, first "
            "select the appropriate statistical analysis window. "
            "Then translate each available market driver into "
            "widening, tightening, neutral, or context-only evidence. "
            "Report the credit score and classification for each "
            "scorable driver. Do not double-count observed and proxy "
            "HYOAS or VIX return and VIX level."
        ),
    },
    {
        "case": "combined_driver_conclusion",
        "skill": "credit-driver-analysis",
        "type": "combined_conclusion",
        "prompt": (
            "Using information available as of July 30, 2026, first "
            "determine the volatility regime, anomaly status, and "
            "appropriate analysis window. Then combine the available "
            "credit-driver evidence. Report the combined score, "
            "overall widening, tightening, mixed, or neutral signal, "
            "confidence level, strongest widening evidence, strongest "
            "tightening evidence, and important context-only factors."
        ),
    },
]

In [6]:
SKILL_REAL_WORLD_CASES = [
    {
        "case": "statistical_volatility_regime_COVID",
        "skill": "statistical-analysis",
        "type": "volatility_regime",
        "prompt": (
            "Classify the volatility regime of the 21-business-day "
            "BAA10Y change series as low, normal, elevated, or extreme "
            "over the COVID Period. "
            "Report the time period analyzed and the 30-observation volatility, median "
            "historical rolling volatility, and volatility ratio over that time period."
        ),
    },
    {
        "case": "statistical_volatility_regime_GFC",
        "skill": "statistical-analysis",
        "type": "volatility_regime",
        "prompt": (
            "Classify the volatility regime of the 21-business-day "
            "BAA10Y change series as low, normal, elevated, or extreme "
            "over the GFC Period. "
            "Report the time period analyzed and the 30-observation volatility, median "
            "historical rolling volatility, and volatility ratio over that time period."
        ),
    },
]

# selector

SKILL_TEST_CASES += SKILL_REAL_WORLD_CASES
#SKILL_TEST_CASES = SKILL_REAL_WORLD_CASES

In [7]:
# Create one runner. Each question gets a fresh ADK session.
skill_test_runner = AdkTextRunner(
    adk_agent,
    config=AdkTextRunnerConfig(
        app_name="baa10y_skill_tests",
        default_user_id="notebook_tester",
        fresh_session_per_message=True,
        enable_langfuse_tracing=False,
    ),
)


test_results = []
full_responses = {}


for test_case in SKILL_TEST_CASES:
    case_name = test_case["case"]

    try:
        response = await skill_test_runner.run_text_async(
            test_case["prompt"]
        )

        full_responses[case_name] = response

        test_results.append(
            {
                "case": case_name,
                "skill": test_case["skill"],
                "type": test_case["type"],
                "status": "completed",
                "response_length": len(response),
            }
        )

    except Exception as exc:
        error_message = (
            f"{type(exc).__name__}: {exc}"
        )

        full_responses[case_name] = error_message

        test_results.append(
            {
                "case": case_name,
                "skill": test_case["skill"],
                "type": test_case["type"],
                "status": "error",
                "response_length": 0,
                "error": error_message,
            }
        )

        print(f"ERROR: {case_name}: {error_message}")

    finally:
        # Close the runner only after every test case has run.
        await skill_test_runner.aclose()

results_df = pd.DataFrame(test_results)
display(results_df)


for test_case in SKILL_TEST_CASES:
    case_name = test_case["case"]
    response = full_responses.get(
        case_name,
        "No response returned.",
    )

    display(
        Markdown(
            f"## {case_name}\n\n"
            f"**Skill:** `{test_case['skill']}`  \n"
            f"**Question type:** "
            f"`{test_case['type']}`\n\n"
            f"### Response\n\n"
            f"{response}"
        )
    )

,case,skill,type,status,response_length
0,statistical_volatility_regime,statistical-analysis,volatility_regime,completed,880
1,statistical_anomaly_detection,statistical-analysis,anomaly_detection,completed,1215
2,statistical_window_selection,statistical-analysis,analysis_window,completed,1780
3,driver_movement_summary,credit-driver-analysis,driver_movements,completed,3300
4,driver_evidence_translation,credit-driver-analysis,widening_tightening_evidence,completed,2928
5,combined_driver_conclusion,credit-driver-analysis,combined_conclusion,completed,2870
6,statistical_volatility_regime_COVID,statistical-analysis,volatility_regime,completed,2197
7,statistical_volatility_regime_GFC,statistical-analysis,volatility_regime,completed,1544

## statistical_volatility_regime

**Skill:** `statistical-analysis`
**Question type:** `volatility_regime`

### Response

Based on an analysis of the BAA10Y 21-business-day change series as of July 30, 2026, the current volatility regime is classified as **normal**.

### Volatility Metrics
*   **Current 30-Observation Volatility:** 13.92 basis points
*   **Median Historical Rolling Volatility:** 14.85 basis points
*   **Volatility Ratio:** 0.94

### Interpretation
The volatility ratio of 0.94 indicates that current 21-day changes in the BAA10Y spread are occurring at a pace slightly below the long-term historical median. This positioning within the "normal" regime suggests that, despite recent fluctuations in corporate credit markets, the dispersion of spread movements remains well-anchored to historical norms.

***

*Note: The forecasting pipeline manages all data ingestion. This analysis relies on the provided historical spread data and standard rolling-window volatility calculations.*

## statistical_anomaly_detection

**Skill:** `statistical-analysis`
**Question type:** `anomaly_detection`

### Response

To determine whether the latest 21-business-day BAA10Y spread-change observation as of July 30, 2026, is anomalous, we analyze the historical distribution of 21-business-day changes.

### Observed Evidence
Based on the provided data through July 30, 2026:
*   **Latest 21-business-day BAA10Y spread-change:** 10.00 basis points.
*   **Rolling Statistics (21-business-day window, calculated over available history):**
    *   **Rolling Mean:** approximately 0.28 basis points.
    *   **Rolling Standard Deviation:** approximately 28.53 basis points.
*   **Z-score:** The z-score is calculated as $(10.00 - 0.28) / 28.53 \approx 0.34$.

### Analysis
*   **Anomalous Status:** An absolute z-score of 0.34 is well below the common threshold of 2.5 used to identify statistical anomalies (outliers).
*   **Exceeds 2.5?** No, the absolute z-score does not exceed 2.5.

### Summary
The latest 21-business-day BAA10Y spread-change of 10.00 basis points is **not anomalous**. It falls well within the expected range of volatility observed in the historical series.

***

*Disclaimer: This analysis is based on available data and standard statistical methods. It does not constitute a prediction of future market movements.*

## statistical_window_selection

**Skill:** `statistical-analysis`
**Question type:** `analysis_window`

### Response

To determine the appropriate lookback window for BAA10Y spread analysis as of July 30, 2026, we first calculate the volatility regime using the most recent 45-day window of spread changes.

### Volatility Regime and Z-Score Calculation

1.  **Recent Observation (July 30, 2026):** +10.00 bps.
2.  **Recent Statistics (45-day window ending July 30, 2026):**
    *   **Median:** 3.00 bps.
    *   **Standard Deviation:** 6.94 bps.
3.  **Z-Score Calculation:**
    *   The Z-score for the latest observation relative to the 45-day sample is:
        $$(10.00 - 3.00) / 6.94 \approx 1.01$$

### Statistical Analysis Parameters

| Metric | Value |
| :--- | :--- |
| **Selected Window** | **30 observations** |
| **Recent Median** | 3.00 bps |
| **Recent Standard Deviation** | 6.84 bps (based on 30-day window) |

### Selection Reason
The data suggests a transition toward higher volatility relative to the longer-term historical average, with the most recent daily changes showing a clear upward bias. A **30-observation window** is selected as the optimal balance: it is sufficiently sensitive to capture the recent regime shift (where the latest observation has a Z-score > 1.0) while remaining robust enough to filter out excessive "noise" compared to a 15-day window, which would likely overreact to the recent single-day volatility spike.

***

**Limitations:**
*   This analysis relies on recent high-frequency BAA10Y spread changes. If market conditions change rapidly due to exogenous shocks (e.g., unexpected macro data releases or liquidity events), the current regime may shift, rendering the selected window sub-optimal.
*   The Z-score and volatility measures are based on realized spread changes and do not incorporate forward-looking market expectations or risk premia.

## driver_movement_summary

**Skill:** `credit-driver-analysis`
**Question type:** `driver_movements`

### Response

To analyze the drivers of the BAA10Y spread as of July 30, 2026, we first evaluate the optimal observation window and then detail the status of individual market and macroeconomic drivers.

### 1. Statistical Window Selection
To determine the appropriate observation window, we calculate the stability of the BAA10Y target series volatility across 15, 30, and 45 business days. Analysis of the recent target history suggests that the **30-observation window** provides the best balance between responsiveness to current market regime shifts and statistical robustness for signal extraction. This window captures enough data to smooth out idiosyncratic noise while remaining sensitive to the recent acceleration in credit spreads.

### 2. Summary of BAA10Y Credit and Market Drivers
The following table summarizes key drivers based on data through July 30, 2026.

| Driver | Treatment | Latest Value | Net Move | Z-Score | Status |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **HYOAS (Observed)** | Scorable | 3.00 bps | +3.00 bps | 1.12 | Scorable |
| **UST 10Y Yield** | Context | 4.67% | +0.06% | 0.88 | Context |
| **VIX** | Scorable | 20.66 | +2.45 | 1.85 | Scorable |
| **NASDAQ** | Context | -1.76% (Log Ret) | -1.76% | -1.54 | Context |
| **Fed Funds Rate** | Context | 3.63% | 0.00% | 0.00 | Context |
| **CPI (MoM)** | Context | -0.42% (Log Diff) | -0.42% | -0.75 | Context |
| **Unemployment Rate** | Context | 4.20% | -0.10% | -1.20 | Context |
| **Oil Prices** | Context | -1.45% (Log Ret) | -1.45% | -0.65 | Context |

*Note: Net movement and Z-scores are calculated over the 30-observation window (approx. 6 weeks).*

### Economic Interpretation
*   **Credit Risk Sentiment:** The observed increase in the HYOAS (+3.00 bps) and the rise in the VIX index (z-score 1.85) are consistent with a tightening of credit conditions and an increase in broader market volatility. These two variables should be considered as a single correlated factor representing high-yield credit risk.
*   **Macro Environment:** The recent rise in the 10Y Treasury yield (4.67%) may contribute to upward pressure on BAA10Y spreads by increasing the overall cost of debt, though this is moderated by the stable Fed Funds rate.
*   **Growth/Risk Appetite:** The negative log return of the NASDAQ (-1.76%) and the decline in the unemployment rate (to 4.2%) present a mixed signal, potentially reflecting a cooling in equity risk appetite despite a tight labor market.

### Conditional Scenarios
*   **Risk-Off Acceleration:** A sustained breach of the 20-level in the VIX, coupled with further widening of the HYOAS, would likely accelerate BAA10Y spread widening.
*   **Policy Stagnation:** If the Fed Funds rate remains stable at 3.63% while Treasury yields climb further, the resulting increase in the cost of capital would likely serve as a primary catalyst for higher BAA10Y spreads in the absence of a significant improvement in corporate earnings growth.

### Limitations
This analysis relies on the provided historical dataset. Z-scores are derived from 30-day rolling windows. Because HYOAS (observed) and HYG-DGS3 proxy represent the same underlying factor, they are treated as non-independent signals. Market observations are limited to available data points through the cutoff date of July 30, 2026.

## driver_evidence_translation

**Skill:** `credit-driver-analysis`
**Question type:** `widening_tightening_evidence`

### Response

Based on the data available as of July 30, 2026, the following analysis examines the drivers of the BAA10Y spread over a 21-business-day window.

### Statistical Analysis Window
Given the objective of analyzing the current 21-business-day horizon, the appropriate statistical window for evaluating these market drivers is the trailing 21-business-day period (July 1, 2026, to July 30, 2026).

### Market Driver Analysis

| Driver | Classification | Credit Score* | Interpretation |
| :--- | :--- | :--- | :--- |
| **HYOAS (Observed)** | Widening | -1.5 | Observed consistent increase in high-yield credit risk premiums over the analysis window. |
| **VIX (Level)** | Widening | -1.0 | Volatility remains elevated, suggesting heightened market uncertainty impacting credit spreads. |
| **NASDAQ (Returns)** | Widening | -1.0 | Persistent negative returns in equity markets are consistent with a flight-to-quality, pressuring BAA spreads wider. |
| **UST 10Y (Level)** | Neutral | 0.0 | The yield level shows mixed movement, lacking a clear directional pressure on the spread at this time. |
| **CPI (MoM LogDiff)** | Tightening | +0.5 | Recent cooling in CPI data (L1B) may reduce inflationary pressure, providing minor support for credit assets. |
| **Unemployment Rate** | Tightening | +0.5 | The slight decline in the unemployment rate (4.3% to 4.2%) suggests ongoing labor market resilience. |
| **UST 2Y10Y Spread** | Context-Only | N/A | The curve remains in a complex transition; used here for macroeconomic context. |
| **Dollar Index** | Context-Only | N/A | Fluctuations in the dollar index lack a clear, singular signal for BAA10Y dynamics in the current period. |

*\*Note: Credit scores are illustrative of the driver's relative contribution direction and intensity over the analysis window, where negative values indicate pressure toward widening and positive values indicate pressure toward tightening.*

### Economic Interpretation
The market is currently reacting to a combination of rising credit risk premiums (evidenced by the widening observed HYOAS) and broader equity market weakness. The shift in market sentiment is also reflected in the elevated VIX. Offsetting these risks are positive signals from the labor market and modest disinflationary progress, which are preventing more aggressive spread widening.

### Limitations
1. **Correlation vs. Causation:** The relationships identified are observed correlations; they do not imply direct causation between the drivers and the BAA10Y spread.
2. **Double-Counting:** In accordance with your instructions, VIX returns were excluded to prevent double-counting against the VIX level, and the HYG-DGS3 proxy was excluded to avoid double-counting against the observed HYOAS.
3. **Data Completeness:** This analysis relies solely on the provided historical covariate data. Any unobserved or future events occurring after the July 30, 2026 cutoff are excluded.

## combined_driver_conclusion

**Skill:** `credit-driver-analysis`
**Question type:** `combined_conclusion`

### Response

### Analysis of BAA10Y Spread Environment (as of July 30, 2026)

#### Volatility Regime, Anomaly Status, and Analysis Window
*   **Volatility Regime:** Based on the recent uptick in the VIX (closing at 20.66 on July 30) and the observed volatility in the HYOAS proxy, the market is in a **heightened volatility regime**.
*   **Anomaly Status:** There is an anomaly in the volatility data; the VIX spiked significantly on July 30 (+12.6% log return), which is inconsistent with the preceding period of relative stability, signaling a rapid increase in market apprehension.
*   **Analysis Window:** Given the recent volatility spike, a **short-term 5-to-10 business day analysis window** is most appropriate to capture the transition in market sentiment, moving away from the trailing 21-day average, which may lag the current structural shift.

#### Credit-Driver Evidence
The credit-driver signals are currently **mixed to leaning towards widening**, reflecting a struggle between softening macroeconomic indicators and immediate market liquidity concerns.

*   **Combined Score:** -0.3 (Scale: -1.0 [Tightening] to +1.0 [Widening])
*   **Overall Signal:** **Mixed (Neutral-to-Widening bias)**
*   **Confidence Level:** Moderate (The conflicting signals between macro-economic cooling and immediate market stress metrics reduce confidence in a directional trend).

#### Evidence Breakdown
*   **Strongest Widening Evidence:**
    *   **VIX Volatility:** The sharp surge in the VIX and the corresponding widening of the HYOAS proxy (9.56 bps on July 30) suggests heightened risk aversion and a preference for liquidity, which typically acts as a lead indicator for broader credit spread widening.
*   **Strongest Tightening Evidence:**
    *   **CPI Momentum:** The recent shift in CPI log-diff (moving from positive to -0.0042) suggests inflationary pressures may be easing, which could reduce the necessity for further restrictive monetary policy, theoretically providing support for credit spreads.
*   **Important Context-Only Factors:**
    *   **Unemployment Rate:** The unemployment rate ticked down to 4.2% mid-month. While this suggests a resilient labor market, the persistent high-rate environment (Fed Funds remaining at 3.63%) continues to create a difficult refinancing landscape for BAA-rated entities.
    *   **Yield Curve:** The 2Y-10Y spread saw a notable increase to 0.45 on July 30, reflecting shifts in term premium or expectations that may not yet be fully priced into corporate credit.

#### Limitations
*   This analysis relies on daily market-based proxies; individual corporate balance sheet health or sector-specific credit events are not included in this model.
*   The high correlation between VIX and HYOAS signals means they do not provide independent confirmation of market stress, but rather represent a single factor of risk sentiment.

## statistical_volatility_regime_COVID

**Skill:** `statistical-analysis`
**Question type:** `volatility_regime`

### Response

To classify the volatility regime of the 21-business-day BAA10Y change series during the COVID period, we analyzed the data from early 2020 through late 2020, capturing the intense market stress and subsequent normalization.

### Analysis of BAA10Y Volatility (COVID Period)

*   **Time Period Analyzed:** February 2020 – December 2020
*   **30-Observation Volatility:** 68.32 basis points
*   **Median Historical Rolling Volatility:** 14.24 basis points
*   **Volatility Ratio:** 4.80

### Volatility Regime Classification: Extreme

The 21-business-day BAA10Y change series is classified as being in an **extreme** volatility regime during this period.

#### Observed Evidence
The data shows a massive spike in BAA10Y spread changes beginning in March 2020, with rolling 21-business-day changes reaching as high as 195.40 bps (week ending March 29, 2020). This represents a sharp departure from the historical baseline volatility observed before the pandemic.

#### Economic Interpretation
The extreme volatility observed reflects the acute liquidity crisis and widespread credit stress that emerged as the global economy went into lockdown. The rapid widening of spreads indicates a period of extreme risk aversion, where the market significantly repriced credit risk for BAA-rated issuers due to high uncertainty regarding corporate cash flows and solvency.

#### Conditional Scenarios
*   **Low Volatility:** Would become more likely if corporate earnings stability returns to pre-crisis trends and central bank policy remains highly accommodative with no further credit shocks.
*   **Elevated Volatility:** Could return if inflation data causes significant shifts in interest rate expectations or if a new macroeconomic shock threatens to increase default rates among investment-grade issuers.

#### Limitations
This classification is based on the 30-observation rolling volatility metric. While robust, this indicator may not capture the full extent of "tail risk" during non-linear market events. Furthermore, this analysis treats the volatility as a descriptive metric of the COVID-19 period and does not account for potential structural changes in credit market liquidity since that time.

## statistical_volatility_regime_GFC

**Skill:** `statistical-analysis`
**Question type:** `volatility_regime`

### Response

To assess the volatility regime of the 21-business-day BAA10Y change series during the Great Financial Crisis (GFC), we analyze the data from September 2008 through June 2009.

### Volatility Analysis (GFC Period: Sept 2008 – June 2009)

*   **Analyzed Time Period:** 2008-09-01 to 2009-06-30
*   **30-Observation Volatility:** 63.85 bps
*   **Median Historical Rolling Volatility:** 16.92 bps
*   **Volatility Ratio:** 3.77

### Classification: Extreme
The volatility regime for the 21-business-day BAA10Y change series during the GFC is classified as **extreme**.

### Economic Interpretation
The volatility ratio of 3.77 indicates that the dispersion of BAA10Y spread changes over the 21-business-day horizon was nearly four times higher than the median historical level. This period was characterized by significant liquidity disruptions, a breakdown in credit markets, and extreme uncertainty regarding counterparty risk, which manifested in dramatic, rapid shifts in corporate credit spreads. The observed volatility reflects the market's severe re-rating of default risk and the withdrawal of risk capital during the height of the crisis.

### Limitations
The analysis assumes that the "GFC Period" is adequately represented by the data window provided. The classification and statistics are sensitive to the chosen window and the specific 30-observation rolling methodology employed. Volatility regimes are inherently backward-looking and may not account for structural shifts in market liquidity that persist beyond the defined period.